### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by adrianp** [adrianp/bag#1]
This is an epic requiring to build the actual user interface. The main features we need to support are:
- [x] List all articles
- [ ] List articles by tags
- [ ] Allow opening original article in new tab
- [ ] Allow marking article as read
- [ ] Allow deleting article
