### ISSUE TITLE
Online version

### ISSUE THREAD

**Issue by adrianp** [adrianp/bag#4]
We should aim to have a publicly available version of bag. Tasks:
- [ ] Use a CI to validate builds
- [x] Separate dev/ production environments
- [x] Deploy on a service as Heroku

**Comment by adrianp** [comment]
Related: #5

**Comment by adrianp** [comment]
Available at: https://getbag.herokuapp.com/
